name: Monitor URLs Múltiples

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # Cada día a las 9 AM

jobs:
  monitor-web:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Más tiempo porque son muchas URLs
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
      
      - name: Run monitor
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        run: |
          python web_monitor.py "$TEAMS_WEBHOOK"
